### ISSUE TITLE
Quickbook no longer builds

### ISSUE THREAD

**Issue by pdimov** [boostorg/filesystem#116]
The superproject builds (https://travis-ci.org/boostorg/boost/builds) have been broken, starting with https://travis-ci.org/boostorg/boost/builds/567103808; the error is

```
tools/quickbook/src/include_paths.cpp: In function ‘void quickbook::include_search_glob(std::set<quickbook::quickbook_path>&, const quickbook::quickbook_path&, std::string, quickbook::state&)’:
tools/quickbook/src/include_paths.cpp:160:14: error: ‘directory_iterator’ is not a member of ‘quickbook::fs’
         for (fs::directory_iterator dir_i(base_dir), dir_e; dir_i != dir_e;
              ^
```

**Comment by Lastique** [comment]
The fix is probably to add #include <filesystem/directory.hpp> or not 
define BOOST_FILESYSTEM_NO_DEPRECATED.

**Comment by pdimov** [comment]
Sounds like it's missing `#include <boost/filesystem/directory.hpp>`, yes. The granular headers don't seem to be documented; is this a supported use case?

**Comment by pdimov** [comment]
```
/home/travis/boost/tools/quickbook/src/include_paths.cpp:15:42: fatal error: boost/filesystem/directory.hpp: No such file or directory
#include <boost/filesystem/directory.hpp>
                                         ^
```

Has this header been newly added?

**Comment by Lastique** [comment]
Yes, it is supported now, it will be released in 1.72. You can include 
filesystem.hpp for now if you want universal code.

**Comment by Lastique** [comment]
Yes, it's in develop only for now.

**Comment by pdimov** [comment]
Seems fine now after https://github.com/boostorg/quickbook/commit/60ecc01fc79eb61beda58172ae3939747df60061.
