### ISSUE TITLE
C++ exception with description "boost::filesystem::resize_file: File too large

### ISSUE THREAD

**Issue by xgdgsc** [boostorg/filesystem#120]
What' s the limit of file resize? I want to resize to 17GB  on a 64bit ubuntu system.

**Comment by Lastique** [comment]
The limit is the max value of `off_t`, as mandated by `truncate` system call. `off_t` is a signed 64-bit integer on 64-bit Linux.

The error you're getting might not be from Boost.Filesystem, but from your OS. You should debug to know for sure.

**Comment by xgdgsc** [comment]
Thanks. Turns out to be an issue of integer multiplication assigned to unsigned integer causing too large file size.
