### ISSUE TITLE
Windows only: filesystem::path::canonical() hangs forever when a junction targets to a directory on different drive

### ISSUE THREAD

**Issue by linux-is-beste** [boostorg/filesystem#123]
Windows only ...

filesystem::path::canonical() hangs forever when a junction points to a different drive

Example:

```
Drive D:
mkdir  \MyJunctionTarget

Drive C:
cd \
mklink /j C:\MyJunction  D:\MyJunction

```
now - a program containing 

   `boost::filesystem::path p(boost::filesystem::canonical("C:\\MyJunction"));`

never returns (hangs forever). See also attached boost_junction_issue.cpp.

note: tested with libboost v1.71.0. But it is also reproducable with libboost v1.57.0.

**Comment by linux-is-beste** [comment]
[boost_junction_issue.cpp.txt](https://github.com/boostorg/filesystem/files/3846720/boost_junction_issue.cpp.txt)

**Comment by linux-is-beste** [comment]
note: when the Junction targets to a directory on a different drive but has a different **name** then it does not hang. Instead it indicates on error with a boolean value of false.

**Comment by GitEvgen** [comment]
It may be losing the drive letter and may be related to https://github.com/boostorg/filesystem/issues/99

**Comment by GitEvgen** [comment]
Some explanations and sample fixes here: https://svn.boost.org/trac10/ticket/10900

**Comment by Lastique** [comment]
Probably fixed by https://github.com/boostorg/filesystem/pull/100.
