### ISSUE TITLE
Docs: Filesystem issue reporting page recommends Trac

### ISSUE THREAD

**Issue by mloskot** [boostorg/filesystem#127]
This page http://boostorg.github.io/filesystem/issue_reporting.html says

> Boost.Filesystem issues such as bug reports or feature requests should be reported via a Boost Trac ticket.
> 
> GitHub pull requests are encouraged, too, although anything beyond really trivial fixes needs a trac ticket.

AFAIU, this is no longer the case and @Lastique is happy to accept all issues and PRs via GitHub. If that is the case, the page needs an update.

**Comment by Lastique** [comment]
I'm not maintaining GitHub pages and have deleted them. The official [docs](https://www.boost.org/doc/libs/1_72_0/libs/filesystem/doc/issue_reporting.html) are actual.

**Comment by mloskot** [comment]
I had no idea. Thanks for removing the obsolete.
