### ISSUE TITLE
GCC suggest-override warnings

### ISSUE THREAD

**Issue by EugeneZelenko** [boostorg/filesystem#135]
Complete list of warnings when Boost 1.72 is built with GCC 7.5 with `-Wsuggest-override` added to `cxxflags`:

<pre>
./boost/filesystem/exception.hpp:72:15: warning: ‘virtual const char* boost::filesystem::filesystem_error::what() const’ can be marked override [-Wsuggest-override]
libs/filesystem/src/codecvt_error_category.cpp:34:19: warning: ‘virtual const char* {anonymous}::codecvt_error_cat::name() const’ can be marked override [-Wsuggest-override]
libs/filesystem/src/codecvt_error_category.cpp:35:20: warning: ‘virtual std::__cxx11::string {anonymous}::codecvt_error_cat::message(int) const’ can be marked override [-Wsuggest-override]
</pre>

Related: boostorg/config#253

**Comment by Lastique** [comment]
https://github.com/boostorg/config/pull/329 needs to be merged first.

**Comment by EugeneZelenko** [comment]
boostorg/config#329 was merged. See also  boostorg/wave#88 for Clang-tidy command line to fix warnings.

**Comment by EugeneZelenko** [comment]
Thank you for help!
