### ISSUE TITLE
Add cirus-ci for freebsd CI

### ISSUE THREAD

**Issue by soroshsabz** [boostorg/filesystem#136]
ITNOA

I think it is good idea to add cirus-ci to create CI for FreeBSD.

**Comment by soroshsabz** [comment]
@Lastique I create PR for this, and I happy to review it :)

**Comment by Lastique** [comment]
My account is restricted by U.S. trade controls law, so Cirrus CI won't register for me, even for the free payment plan.

I won't be registering Cirrus CI, and any other service that discriminates users based on their country.

**Comment by soroshsabz** [comment]
Thanks for attention to this issue, I was surprised that you see this message, I think this tyrannical rule (
message ) is only for Iranian and few and limited other countries. but I think you got some misunderstanding, this message does not means Cirrus CI or other marketplace App and service is prohibited for you, this rule is enforced by GitHub and apply in User level not App level as I know ( Of course, I may have mistake). so I don't think Cirrus CI has any restriction or discriminates. so If you agree with me, please open this issue

thanks for attention :)

**Comment by Lastique** [comment]
This isn't just a GitHub rule, this restriction applies to any US-based company doing business with parties under US trade sanctions. For example, it applies to Google (Gmail, Youtube) as well. However, these companies still provide free (non-commercial) services to everyone. Cirrus CI, on the other hand, doesn't provide services even to non-commercial users. Maybe there's a technical limitation imposed by GitHub, I don't know, but the fact remains - users, myself included, are discriminated, which I find unacceptable.
