### ISSUE TITLE
Warning free build

### ISSUE THREAD

**Issue by Flamefire** [boostorg/filesystem#143]
Would you mind activating `-Wall -Wextra -pedantic` with `-Werror` for CI? Can be done via Jam, see https://github.com/boostorg/nowide/blob/2e543e987d4e3c1e9960fb67166594d86dfba033/test/Jamfile.v2#L12-L20

This avoids warnings for downstream users, like currently:
```

/home/runner/work/nowide/nowide/libs/filesystem/include/boost/filesystem/operations.hpp:59:26: error: comma at end of enumerator list [-Werror=pedantic]
   overwrite_existing = 1u,      // Overwrite existing file

```

**Comment by Lastique** [comment]
I don't support warning-free builds, especially not in "warnings as errors" mode.

I will fix reasonable warnings, like this one, upon report.

**Comment by Flamefire** [comment]
Ok, but wouldn't it be easier to have those on CI instead of waiting for a report? Especially for releases reports might be to late. The "warnings as errors" mode is just so it can be caught on CI

**Comment by Lastique** [comment]
I don't want a CI broken by a warning. Especially, when a new compiler comes out with a bunch of new warnings.

**Comment by Flamefire** [comment]
I don't see anything bad by that. Warnings *may* be bugs (although most often they are not) so being forced to fix or ignore a particular warning is a good thing. And downstream users will not face that warning later on either.

And "when a new compiler comes out": It isn't like this is going to break your CI out of a sudden. You got to  actively add that compiler to CI. And then new warnings mean new kinds of errors can be detected. Example: Moved-from usage detection was added not so long ago.

**Comment by Lastique** [comment]
> although most often they are not

Exactly. In my experience, warnings are often nuisance rather than a helper. Sometimes, you have to cripple the code instead of improving it to get rid of the warning. I will recommend users to disable such warning.

BTW, I don't consider littering code with `#pragma`s improving it either. I understand it makes user experience better, and that is the only reason I would consider adding yet another one to silence a warning. But I'm not going to waste my time to actively test and pre-emptively catch and silence every warning on every compiler. I have other things to do.

**Comment by Flamefire** [comment]
Sure I understand. Been through that already and I know it is some work in the beginning. And some warnings (especially MSVC) annoy the sh*t out of me but I decided to bite the bullet and silence warnings so real issues don't stay undetected. It also makes you reconsider the code which it warns about and sometimes you find a real issue related to the warning. IMO that is worth the struggle.

Example worth checking:
```
libs/filesystem/src/operations.cpp:1032:30: warning: missing initializer for member ‘stat::st_dev’ [-Wmissing-field-initializers]
   struct ::stat from_stat = {};
```
Could be a real issue. 

In the end it's your decision just wanted to bring up the arguments although I guess you know them already ;)

**Comment by Lastique** [comment]
> Example worth checking

That is an example of a bogus warning, as the code clearly zero initializes all members, as required by the standard. That is the intention of the code and trying to fix it does not improve the code - quite the opposite.

**Comment by Flamefire** [comment]
> trying to fix it does not improve the code - quite the opposite.

I'm quite advanced in C++ and would still need to look up all 300 or so initializations that can happen to be 100% sure this is zero-initialization. So I wouldn't be sure what that code does from a first look. While a `struct ::stat from_stat; memset(..., 0)` would be very clear. So for me it would improve the code. Just as an example that also "improving" is relative to the reader.

**Comment by Lastique** [comment]
> While a `struct ::stat from_stat; memset(..., 0)` would be very clear.

Right, and while doing that you'll forget the `std::` qualification or include `cstring`. Or mess up the size, if the variable is an array. So many things can go wrong with `memset` and friends... :) I'll prefer the built-in initialization syntax - it is shorter, it's safer, and it doesn't add new dependencies. And as long as I'm dealing with the code, its semantics is clear.
