### ISSUE TITLE
boost::filsystem::copy fails to copy recursively if error code parameter provided

### ISSUE THREAD

**Issue by x-santiaga-x** [boostorg/filesystem#152]
In test/copy_test.cpp test will fail in test_copy_dir_default if we change
```
    fs::copy(root_dir, target_dir);
```
to
```
    boost::system::error_code ec;
    fs::copy(root_dir, target_dir, ec);
```

because of checking stat of non-existent destination directory before creating it.

**Comment by Lastique** [comment]
Thanks for the report.
