### ISSUE TITLE
boost::filesystem::exists case insensitive on macos

### ISSUE THREAD

**Issue by zgpio** [boostorg/filesystem#153]
version: boost 1.70.0
system: macos 10.14

Expected behavior: boost::filesystem::exists should be case sensitive

test case: "fool.txt", "foOl.txt"

**Comment by Lastique** [comment]
Boost.Filesystem does not perform case conversion and uses `stat` system call to implement `status` (and, consequently, `exists`). If the test says the file exists then that is what the underlying filesystem reports.
