### ISSUE TITLE
Feature Request: trash bin support

### ISSUE THREAD

**Issue by zgpio** [boostorg/filesystem#155]
I wonder if there are plans to support trash bin, or why not support it.

**Comment by Lastique** [comment]
There are no plans to implement this. Trash bin is a feature of a Desktop Environment rather that a filesystem. Not every DE supports that feature and not every system has a DE to begin with, so the feature is not universally available. I imagine, for some DEs supporting this feature would require unreasonable dependencies for Boost.Filesystem. I think, this feature needs to be supported at a higher level than Boost.Filesystem.
