### ISSUE TITLE
Link failures on Windows due to missing crypt lib dependencies

### ISSUE THREAD

**Issue by Flamefire** [boostorg/filesystem#156]
5d1b14df515de57b885afe105cea13a4b092a2a7 introduces a regression: Windows consumers using BoostConfigs or CMake FindBoost now won't link to the required libraries where they previously did, leading to link failures.

Is it possible to keep the MSVC auto link statements?

Also: How is a consumer supposed to know if he has to link against Advapi32 or bcrypt when using an existing Boost installation? Is there some config file or header to fix?

Long-term it would be best to be able to declare such dependencies in the generate CMake configs and in a generated config header or similar (for other build systems). Because now you have to link to one out of the 2 or none of the crypt libs without knowing how Boost was build, or am I missing something?

**Comment by Lastique** [comment]
> Is it possible to keep the MSVC auto link statements?

Technically, it's possible, but I don't want to do this. It is an MSVC-specific solution, which will not work when auto-linking is not supported, meaning that the build system based linking must still be implemented. I'd rather have it in a single place and work the same way everywhere.

The dependencies are selected and declared in the build system - both Boost.Build and CMake. Consumers importing those build systems will keep linking as they did before.

Consumers not importing the library build systems may be affected, if they link to a static library. They will have to reproduce the same checks we do in our scripts in their build system or just hardcode the required libraries. Or just switch to a shared library of Boost.Filesystem, which already has everything linked.

I don't know how CMake FindBoost config files are generated. If they don't include library dependencies then I would say they should be updated to include those. If there is a way to do that from Boost.Filesystem side, I'm not aware of it. @pdimov Could you comment on this?

**Comment by Flamefire** [comment]
My point is: Users usually use the system provided Boost (through packages) or build it with b2 as building Boost with CMake is not yet working   
The installed Boost will have no mention what library was used to build Boost and hence which library the user needs to link because B2 doesn't write this information out (CMake does)

So now something that worked before is broken and users have to do quite some work to workaround this as "reproduce the same checks we do in our scripts in their build system" may not be entirely trivial. Maybe it is even wrong if the Boost build environment and their environment is slightly different. (Not sure here, but maybe in the latter the library is found while it wasn't when Boost was build or the other way round) So I'm quite certain users will be confused and will complain once this is released.

While I agree with that this is  a "MSVC-specific solution, which will not work when auto-linking is not supported,", MSVC is still the most widely used compiler on Windows. (Does clang-cl support this too?`I'd guess yes) So for the majority of the users this solution works. Windows users usually don't use shared libs either because that is a huge PITA, so they likely use static Boost libs

The (upstream) CMake FindBoost script would need to add this check too, but the CMake people usually resist and say that the library project (here: Boost) should do that work as maintaining such a module outside a library is... hard.

The Boost CMake Configs generated by B2 currently don't have the ability to declare dependencies which is a shortcoming which might not be solved before the upcoming release.

So in order to not alienate the majority of Windows users of Boost.Filesystem with the upcoming release I'd strongly recommend adding those few lines back.

**Comment by Lastique** [comment]
Although I disagree with your assessment of severity of this issue, I restored the auto-linking, with a deprecation period. Eventually, I want to remove that code, preferably when CMake config scripts expose third-party dependencies of Boost libraries.

I also restored Windows CE-specific library to link against.

Note that users need to specify Boost dependencies of Boost libraries anyway because Boost auto-linking is disabled while Boost is being compiled. This is not a new problem, so static library users have learned to live with it somehow.

**Comment by Flamefire** [comment]
Thank you!

For the last point: This is currently solved by CMakes FindBoost which has a list of Boost libs with its Boost dependencies per version (not great...) and Boosts CMakeConfig which gets it by querying B2, see https://github.com/boostorg/boost_install/blob/ea28ed441fb04f2c5839e99e37f4c173fcfd48ec/boost-install.jam#L432   
So the "live with it somehow" is currently (mostly): Use CMake

**Comment by pdimov** [comment]
This also broke Beast's CMakeLists.txt file.

All Windows compilers except GCC support autolinking.

In principle boost_install should look for third-party dependencies and make the CMake imported targets link to them, but this is complicated by the fact that I have no idea how to do it. The existing dependency collecting code was written by Steven and it took him a number of tries to get it right.

> Note that users need to specify Boost dependencies of Boost libraries anyway because Boost auto-linking is disabled while Boost is being compiled.

I can't think of a case where users need to specify Boost dependencies manually. (Well, except for when the autolink statements aren't quite right, as was f.ex. the case with Timer before I fixed it in https://github.com/boostorg/timer/commit/cb59c5cff1d044d875b4c5984a46efcffa6c9df5. This happens when a library uses another library only in the .cpp files.)

**Comment by Lastique** [comment]
> All Windows compilers except GCC support autolinking.

Meaning that all other configurations remain broken until users specify dependencies manually. And I don't mean only on Windows.

> In principle boost_install should look for third-party dependencies and make the CMake imported targets link to them, but this is complicated by the fact that I have no idea how to do it.

If this is not easy to do with Boost.Build, maybe we could do it with CMake? Or have a common source to specify dependencies, like a file or a script that spits out dependencies, or a variable with the list of dependencies. Or any other way with library's assistance. Though, not having to duplicate this information would be preferable, of course.

> I can't think of a case where users need to specify Boost dependencies manually.

I think I had user reports to that effect in Boost.Log, but I don't remember the details. The point is this can happen, and probably has happened.

**Comment by pdimov** [comment]
It happens, but isn't the norm. As I said, it happens when A uses B but A.hpp doesn't include B.hpp (which autolinks to B), so A.hpp needs to be fixed to autolink to B in addition to A.

This is only an issue when linking manually. The CMake configs do handle Boost dependencies.
