### ISSUE TITLE
Filesystem directory_iterator can not return file path to me and file status is error. I'm run on iOS platform.

### ISSUE THREAD

**Issue by onedou** [boostorg/filesystem#159]
![image](https://user-images.githubusercontent.com/3422640/91375261-c3e5d780-e84c-11ea-9e3e-344bb84db477.png)

**Comment by Lastique** [comment]
1. Please, don't post screenshots of your code, they are not helpful. Post code in plain text instead.
2. Please, post a minimal compilable code sample that reproduces the problem.
3. If you're getting a default-constructed `directory_entry` from `directory_iterator` then that is most probably a result of a runtime error. In this case you should inspect the `error_code` you're getting.

**Comment by onedou** [comment]
Ok, Thank you, I'll keep looking for the problem. If there's progress, I'll send a message to here

**Comment by onedou** [comment]
I build a empty project. but that seems like origin project.

![image](https://user-images.githubusercontent.com/3422640/91663507-cdf12a00-eb1b-11ea-964d-13ff7e54fb6d.png)

**Comment by onedou** [comment]
m_perms is no_perms

**Comment by Lastique** [comment]
As I said before, I have no idea what is going on or what the problem might be without a compilable reproducer code sample.

**Comment by onedou** [comment]
windows and mac are normal

**Comment by onedou** [comment]
The source code is here. https://github.com/LiXizhi/NPLRuntime/tree/cp_old/NPLRuntime/Platform/iOS

**Comment by Lastique** [comment]
That is not a minimal repro, I cannot test it.

Did you debug? What does `readdir` return? What is the directory structure you're iterating over?

**Comment by onedou** [comment]
/Users/xxxxx/Library/Developer/CoreSimulator/Devices/xxx-xxx-xxxx/data/Containers/Data/Application/xxxxxx-xxxxx-xxxxxx/Documents

**Comment by onedou** [comment]
1. That can create folders and files.
2. I run my simple project on iOS simulator. The `m_value` is 256 and the `m_perms` is owner_read.

My simple project are here.
http://service.schoolchat.org:10180/big/ios-app

**Comment by Lastique** [comment]
> My simple project is here.

I cannot run that. A minimal repro is a single .cpp file, preferably with a single function `main()` that reproduces the problem.

I also don't have an iOS environment, I can only test on Linux.

> What does `readdir` return? What is the directory structure you're iterating over?

**Comment by onedou** [comment]
OK,Thanks a lot.I think that maybe iOS SDK problem, but boost 1.69.0 is correct.

**Comment by Lastique** [comment]
Also check if you are affected by https://github.com/boostorg/filesystem/issues/147.

**Comment by onedou** [comment]
> Also check if you are affected by #147.

Thank you. That work for me now!
