### ISSUE TITLE
const std::string return value results in pessimization

### ISSUE THREAD

**Issue by kauboy26** [boostorg/filesystem#160]
Hi,

I was taking a look at path.hpp and found that some functions, such as [`path::string()`](https://github.com/boostorg/filesystem/blob/d855c2d37734262e3db5fa938c384d16769b8f05/include/boost/filesystem/path.hpp#L435), returned by value but were marked as const.

So for example, if I had a path object `path1`, and then I made a `std::string` object `s` as follows:  
```  
std::string s = path1.string();  
```  
The above would call `std::string`'s copy constructor rather than its move constructor.

I was wondering if this was intended behavior, as we are missing a chance to optimize.

Thank you!

**Comment by Lastique** [comment]
Thanks for the report.
