### ISSUE TITLE
"recurrent_directory_iterator" inside std::filesystem Doesn't support files with "Unicode Characters"

### ISSUE THREAD

**Issue by a1-kh** [boostorg/filesystem#170]
I do believe that the problem is with the way "std::recursive_directory_iterator" handles the files.
I tried to only print the files paths from the iterator with :

cout << file.path().string();

and it printed the files until it reached a file with Unicode Characters and crashed.
I tried :

cout << file.path().u8string()

.. it didn't crash , but the Unicode Characters are messed up completely.
I tried :

wcout << file.path().u8string()

.. no luck
I tried :

wcout << file.path().u16string()
wcout << file.path().u32string()

.. u16string() and u32string() doesn't exists
the error :
Unhandled exception at 0x00007FFB078C3E49 in ConsoleApplication1.exe: Microsoft C++ exception: std::system_error at memory location 0x000000DD992FE8D8.
here in filesystem :
[[noreturn]] inline void _Throw_system_error_from_std_win_error(const __std_win_error _Errno) {
_THROW(system_error{_Make_ec(_Errno)});
}

I forgot also to mention that i tried "std::wcout << file.path().wstring();" yesterday, but that didn't work too cause it skipped the Unicode files all together .

Specs :
Windows 10. Visual Studio 2019 and the c++17 standard, with everything on default.

**Comment by Lastique** [comment]
Report this to your standard library vendor. Boost.Filesystem is not std::filesystem.
