### ISSUE TITLE
statx syscall on boost-1.75

### ISSUE THREAD

**Issue by skypool** [boostorg/filesystem#173]
I'm using boost-1.75. On a Linux Kernel < 4.11 the statx is not yet available but BOOST_FILESYSTEM_HAS_STATX_SYSCALL is nevertheless set. It seems the code in 'has_statx_syscall.cpp' has no effect.

**Comment by Lastique** [comment]
You're probably building with kernel headers not matching the kernel you're running the compiled binaries on. Duplicates https://github.com/boostorg/filesystem/issues/172 and https://github.com/boostorg/filesystem/issues/164.

**Comment by paresy** [comment]
This also fails for any older docker builds: docker/for-linux#208

If you have an outdated docker version (e.g. you use Docker on Synology) upgrading to Boost 1.75 will fail miserably.
