### ISSUE TITLE
Consider adding a flag for ignoring fchmod errors in copy_file

### ISSUE THREAD

**Issue by Lastique** [boostorg/filesystem#179]
As described in https://github.com/boostorg/filesystem/issues/178, there are cases when `fchmod` consistently fails for a particular filesystem. This causes `copy_file` failure, although the file is successfully copied, though without setting the original access mode and permissions. It may be desirable to suppress the error from `copy_file` if `fchmod` fails.

One possible solution is to add a new flag in `copy_options` to ignore errors from `fchmod`.

Side note: It may be worthwhile to detect NFS with [`statfs`](https://man7.org/linux/man-pages/man2/statfs.2.html) (for it `f_type` should be `NFS_SUPER_MAGIC`) and only set `S_IWUSR` permission when the target file is on NFS. This way we may not have to change the target file permissions after copying. Although, if a filesystem does not support `fchmod`, it is possible that `fstat`/`statx` for the target file returns a different mode from the original file, which means we will try calling `fchmod` anyway.

**Comment by kkumar45** [comment]
@Lastique: Any update on it, when it will be planned?

**Comment by Lastique** [comment]
No updates, unfortunately. I haven't got around to it.

**Comment by kkumar45** [comment]
@Lastique Can you please consider it? Our customers are impacted due to this.
