### ISSUE TITLE
Not working in Google Cloud Run (uses gVisor)

### ISSUE THREAD

**Issue by jgsogo** [boostorg/filesystem#191]
I've created a docker container (`ubuntu:focal`) with a C++ application that is using `boost::filesystem` (v1.76.0) to create some directories while processing data. It works if I run the container locally, but it fails when deployed to Cloud Run.

A simple statement like
```
boost::filesystem::exists(boost::filesystem::current_path())
```
fails with _"Invalid argument '/current/path/here'"_. **It doesn't work in this C++ application, but from a Python app running equivalent statements, it does work.**

Reading [the docs](https://cloud.google.com/run/docs/reference/container-contract#sandbox) I can see Cloud Run is using gVisor and not all the system calls are fully supported (link: https://gvisor.dev/docs/user_guide/compatibility/linux/amd64/), nevertheless I would expect simple calls to work: check if a directory exists, create a directory, remove,... 

---

Tried with std::filesystem (C++17), it works.

**Comment by Lastique** [comment]
Sorry, there's no chance I'm going to be able to debug this. Please, investigate this further. In particular, reduce the test case to a single call and preferably down to a single system call. Patches are welcome, of course.

**Comment by Lastique** [comment]
Any updates on this? Does it still fail with the current develop?

**Comment by Lastique** [comment]
Since there's no reply and I'm not going to be able to debug this, I'm closing this ticket.
