### ISSUE TITLE
windows_file_codecvt class is not inside boost:: namespace

### ISSUE THREAD

**Issue by naelolaiz** [boostorg/filesystem#195]
When doing a windows build, windows_file_codecvt class is included in path.cpp, which is in the global namespace.
This is a special problem when using a boost custom namespace to avoid symbols collision when linking with different boost versions, since windows_file_codecvt gets exported unprefixed.

**Comment by Lastique** [comment]
Thanks for the report.

Linking multiple Boost versions is not supported and may fail in subtle ways. But moving `windows_file_codecvt` into a namespace makes sense.

**Comment by naelolaiz** [comment]
Wow, that was fast! 
Thank you!
