### ISSUE TITLE
Functions fail when used inside docker container in Jetson modules (ARM)

### ISSUE THREAD

**Issue by Andyalevy** [boostorg/filesystem#196]
When trying to run a project using functions from the filesystem project, in a container running inside a jetson machine, functions such as `exists` or `is_empty` fail with the following error: `boost::filesystem::status: Function not implmented: `

It was done on a Jetson Xavier AGX flashed with Jetpack 4.5. Using boost 1.76 and GCC 7. The base image for the docker image was: nvcr.io/nvidia/l4t-base:r32.5.0

**Comment by Lastique** [comment]
Most likely duplicates https://github.com/boostorg/filesystem/issues/172.
