### ISSUE TITLE
path::lexically_normal issue under Windows

### ISSUE THREAD

**Issue by d0nc1h0t** [boostorg/filesystem#200]
After upgrading boost to version 1.77 beta 1, the function path::lexically_normal under Windows OS changed.
```c++
  const boost::filesystem::path path{ "C:/Directory/Folder" };
  const auto normal = path.lexically_normal();
```
Boost 1.76 - 'C:\Directory\Folder' (similar to std::filesystem::path)
Boost 1.77 beta 1 - 'C:/Directory\Folder'

**Comment by Lastique** [comment]
Thanks for the report.
