### ISSUE TITLE
add isHidden()

### ISSUE THREAD

**Issue by ChungZH** [boostorg/filesystem#202]
Add `isHidden()` to know if the file is hidden.

**Comment by ChungZH** [comment]
Many libraries support this, like [poco](https://pocoproject.org/docs/Poco.File.html#14597), [Qt](https://doc.qt.io/qt-5/qfileinfo.html#isHidden)

**Comment by Lastique** [comment]
Boost.Filesystem is mostly modeled on POSIX and on POSIX systems there is no "hidden" attribute, it's just a file naming convention. For example, there would be no way to represent it in `file_status`, on which all `is_*` functions rely.

**Comment by ChungZH** [comment]
I see. Thank you.
