### ISSUE TITLE
boost::filesystem::create_directory: File exists:

### ISSUE THREAD

**Issue by computervisionlearner** [boostorg/filesystem#211]
Hi, everyone:
    I used boost 1.75 version in the mirror of the centos physical machine and there was an error as shown in the title。Through the search engine, I found a question consistent with my situation:
> https://stackoverflow.com/questions/67256984/boostfilesystemexists-throws-operation-not-permitted-exception-on-centos-8-d

Would you mind telling me how to solve it? Looking forward your kind reply, thks!!!!

**Comment by Lastique** [comment]
Duplicates https://github.com/boostorg/filesystem/issues/210.
