### ISSUE TITLE
Invalid include of hash_fwd

### ISSUE THREAD

**Issue by Flamefire** [boostorg/filesystem#215]
https://github.com/boostorg/filesystem/commit/2e6cc63e653e5f99f191e8733013617521dc69ab introduced a bug:
It uses hash_range in an inline function but has only hash_fwd.hpp included. I.e. a full use with only the forward declaration header included.

When using the compiler flag `-fkeep-inline` it leads now to undefined reference...

**Comment by Lastique** [comment]
This is not a bug. Users are supposed to include `boost/container_hash/hash.hpp` before using hash functions. What Boost.Filesystem defines is a plug-in for Boost.ContainerHash.

**Comment by Lastique** [comment]
As for `-fkeep-inline`, I've committed a workaround that should fix the linking issue.
