### ISSUE TITLE
Missing path operator+=(path p) in 1.78

### ISSUE THREAD

**Issue by achow101** [boostorg/filesystem#223]
I recently updated to boost 1.78 and a project which uses boost::filesystem no longer compiles, emitting the error:

```
error: no match for ‘operator+=’ (operand types are ‘fs::path’ and ‘std::remove_reference<fs::path&>::type’ {aka ‘fs::path’})
```

It seems to be that `path& operator+=(const path& p);` is missing from `filesystem/path.hpp` in 1.78 (as it exists in previous versions), although the documentation states that this function still exists.

If I change to using `concat(p)`, it works, but `path& concat(const path& p);` is not available in older versions of boost.

**Comment by Lastique** [comment]
The `path` argument is accepted by [this](https://github.com/boostorg/filesystem/blob/04c6e582be42dbce428d5f04ca14a8d23caafedd/include/boost/filesystem/path.hpp#L433-L440) `operator+=`. Please provide a small compilable repro.

**Comment by achow101** [comment]
It seems like the issue occurs when something subclasses `boost::filesystem::path`. https://github.com/achow101/super-carnival exhibits this failure.

**Comment by Lastique** [comment]
Thanks for the report.

BTW, you can work around this by explicitly casting the argument to `boost::filesystem::path`.
