### ISSUE TITLE
[1.74.0] non-virtual-dtor in codecvt_error_cat

### ISSUE THREAD

**Issue by Sil3ntStorm** [boostorg/filesystem#232]
libs/filesystem/src/codecvt_error_category.cpp:27:9: warning: '(anonymous namespace)::codecvt_error_cat' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]
  class codecvt_error_cat : public boost::system::error_category
        ^

**Comment by Lastique** [comment]
For the record, the warning was not appearing in the official Boost build. I'm assuming you're building Boost using your own build system that is not equivalent to the official build. You should change your build system behavior to match the official build system.

That said, I silenced the warning anyway, just in case if the warning is manually enabled in the command line.
