### ISSUE TITLE
Handling of Windows system file status broken since 1.79.0

### ISSUE THREAD

**Issue by MarcelRaad** [boostorg/filesystem#234]
Since commit https://github.com/boostorg/filesystem/commit/97722a3107d136eebe9425804fe0d13eab3ce2bc, calls like these fail on Windows 10:
`boost::filesystem::is_directory(L"C:\\System Volume Information")`
`boost::filesystem::is_symlink(L"C:\\DumpStack.log")`

This is because `CreateFileW` now fails with `ERROR_ACCESS_DENIED`, while the previously used `GetFileAttributesW` succeeded.

**Comment by Lastique** [comment]
Note that `std::filesystem::symlink_status` also returns "Access denied" for "C:\System Volume Information". `std::filesystem::status` succeeds. I'm not sure I like this kind of inconsistency.

**Comment by MarcelRaad** [comment]
I can confirm that the patch works great. Thanks a lot!

**Comment by Lastique** [comment]
What filesystem is H:? Can you debug this case?

Assuming that you're not passing an `error_code` and there is no exception, WinAPI calls don't fail in your case, so this is not the same issue as the one that was originally reported here. Please open a new issue with all additional information you find.

**Comment by TMeindl** [comment]
Ah, sorry, there where other changes in the operations.cpp file; I just used this patch for testing. I can confirm that with boost version 1.80 boost::filesystem::is_directory() works as expected.
