### ISSUE TITLE
directory_iterator_construct fails on FAT32 formatted flash drive under Windows

### ISSUE THREAD

**Issue by chenche23** [boostorg/filesystem#237]
I believe the root cause and workaround is similar to Issue #236 .

I am using v1.79 compiled with msvc-14.1.
I try to create a directory Iterator on the root directory of a flash drive (say E:/)
```
boost::system::error_code error;
boost::filesystem::directory_iterator it("E:/", error);
```

That fails with error code 87 (ERROR_INVALID_PARAMETER)

dir_itr_create() uses get_file_information_by_handle_ex() in directory.cpp(775). When I jump to the else-branch using GetFileInformationByHandle(), the Iterator is created successfully.

**Comment by truemanc** [comment]
I'm using exFat formatted disk under windows.

Hit the same issue via remove_all() which depends on dir_itr_create() . dir_itr_create() uses the same approach as #236.

**Comment by Lastique** [comment]
Thanks for the report.

**Comment by truemanc** [comment]
Using the latest code, I confirm remove_all() passes on my exFat formatted drive under Windows.

**Comment by Lastique** [comment]
Thank you for testing.
