### ISSUE TITLE
On Windows, `absolute("C:")` returns the current working directory?

### ISSUE THREAD

**Issue by emmenlau** [boostorg/filesystem#251]
I've just found a strange behavior that seems so unlikely that maybe I'm doing something wrong? I'm using boost 1.80.0 current official release.

When I call `absolute("C:")` it returns my current working directory. Is that expected? Is `C:` not a valid absolute path on Windows?

**Comment by Lastique** [comment]
"C:" is not an absolute path, it refers to the current path on drive C.
