### ISSUE TITLE
dispatch is deprecated

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/filesystem#252]
But filesystem still uses it:
https://github.com/boostorg/filesystem/blob/bb7dc550d5274ccb76e774c2b996333977de4347/include/boost/filesystem/path.hpp#L619

**Comment by Lastique** [comment]
Only certain `dispatch` overloads are deprecated, others are not. If you're getting a deprecated warning then you are passing an argument that is not a string or a C-style string, and *that* is deprecated. Also, I replied on the ML.
