### ISSUE TITLE
std/boost remove_filename different output

### ISSUE THREAD

**Issue by marakew** [boostorg/filesystem#271]
[https://wandbox.org/permlink/iQDub9HJdmdSzqj6](https://wandbox.org/permlink/iQDub9HJdmdSzqj6)

```
C:/windows/disk/path/some/div/run.exe
"C:/windows/disk/path/some/div/"
"C:/windows/disk/path/some/div"
std parent_path "C:/windows/disk/path/some/div"
boost parent_path "C:/windows/disk/path/some"
```

is it boost correct  or std correct ?

**Comment by Lastique** [comment]
They both are. Boost.Filesystem v3 is not equivalent to std::filesystem.
