### ISSUE TITLE
Tutorial references scripts that have been removed

### ISSUE THREAD

**Issue by rdimartino** [boostorg/filesystem#276]
I was trying to follow along the tutorial which says to [compile and test the examples using the provided scripts](https://github.com/boostorg/filesystem/blob/develop/doc/tutorial.html#L75-L76) but it looks like those scripts were removed in https://github.com/boostorg/filesystem/commit/bb116b96f6633b6c4e29b5a3eb31f18fcaaf5baa

Not sure if the scripts should be added back or the tutorial docs should be updated.

**Comment by Lastique** [comment]
Thanks for the report.
