### ISSUE TITLE
ODR violations in boost::filesystem::path

### ISSUE THREAD

**Issue by frankmiller** [boostorg/filesystem#279]
There are a number of inline member functions in `boost::filesystem::path` that have different implementations depending on the definition of `BOOST_FILESYSTEM_VERSION`. When compiling boost.filesystem, `BOOST_FILESYSTEM_VERSION` is [always set to 4](https://github.com/boostorg/filesystem/blob/9a49c4f3f4624d445dad875ee3d72f2d364c5e39/include/boost/filesystem/config.hpp#L29). If a program uses boost.filesystem with `BOOST_FILESYSTEM_VERSION` set to 3, [which is the default](https://github.com/boostorg/filesystem/blob/9a49c4f3f4624d445dad875ee3d72f2d364c5e39/include/boost/filesystem/config.hpp#L31), then I believe this is an [ODR violation](https://en.cppreference.com/w/cpp/language/definition) because the program now has multiple definitions of the same function that do not consist of the same sequence of tokens.

**Comment by Lastique** [comment]
Duplicates https://github.com/boostorg/filesystem/issues/243.

Yes, this is formally an ODR violation. In practice, though, it works due to forced inlining of these methods. This will get resolved when v3 is dropped.

**Comment by frankmiller** [comment]
For the record, there is no inlining in a debug build. Also, I suspect LTO is interacting with inlining in unexpected ways, at least with msvc. I'm happy to resolve the issues I'm seeing on my end by moving to version 4. I just wanted to make sure the upstream maintainers were aware.

**Comment by Lastique** [comment]
Yes, debug build needs fixing.
