### ISSUE TITLE
1.82.0 beta 1 build broken on OpenBSD

### ISSUE THREAD

**Issue by brad0** [boostorg/filesystem#283]
With 7509619c9eea5673b0db14d43ffcef62d44ba51e adding the use of ```--no-undefined``` with the linker broke the build on OpenBSD. 

Shared libraries that reference libc functions cannot use ```--no-undefined``` on OpenBSD.

**Comment by Lastique** [comment]
> Shared libraries that reference libc functions cannot use `--no-undefined` on OpenBSD.

Why? What symbols are missing?

**Comment by Lastique** [comment]
Nevermind, I found a few reports online about this problem. Seems like `-Wl,--no-undefined` is completely broken for shared libraries on OpenBSD.

Thanks for the report.
