### ISSUE TITLE
directory_iterator is broken for smb1 locations on windows

### ISSUE THREAD

**Issue by chrisdecker08** [boostorg/filesystem#284]
`directory` is a smb1 location, either a mapped network drive or UNC path

```
bool isDir = fs::is_directory(directory); <- Works
fs::directory_iterator iter(directory); <- throws an exception
```

The exception seems to originate at directory.cpp:842 with an error code of 124 (ERROR_INVALID_LEVEL)

**Comment by Lastique** [comment]
Could you test if https://github.com/boostorg/filesystem/commit/fcc1bf3eca15323b90f2df042464668b0d131698 fixes the problem for you?

**Comment by chrisdecker08** [comment]
This works for me locally, let me get a test build including this patch out to some users in order to do the final verification.

**Comment by chrisdecker08** [comment]
This seems to work for our users.  There appear to be some users with miscellaneous issues not related to smbv1, however I hesitate to file any bugs unless we can reproduce or at least establish a pattern.

**Comment by Lastique** [comment]
Ok, thanks for the report and testing.
