### ISSUE TITLE
error_code parameter not reset in directory_entry::status()

### ISSUE THREAD

**Issue by gfgtdf** [boostorg/filesystem#291]
The documentation https://www.boost.org/doc/libs/1_83_0/libs/filesystem/doc/reference.html#status specifies 

> If, during attribute determination, the underlying file system API reports an error, sets ec to indicate the specific error reported. Otherwise, ec.clear().

But it was observed that `ec.clear()` is no longer called in all cases, see for example https://github.com/wesnoth/wesnoth/issues/7866

**Comment by Lastique** [comment]
Please, provide a reproducer or at least more information as to what's going on. `ec.clear()` is being called [here](https://github.com/boostorg/filesystem/blob/e65ddb6ef21697970f7d1438f7a46c5233940059/src/operations.cpp#L4282C21-L4283C21).

**Comment by gfgtdf** [comment]
I see i linked the wrong documentation, this issue is about `directory_entry::status()` not the `status()` free  function, I think what i said still applies though: https://www.boost.org/doc/libs/1_83_0/libs/filesystem/doc/reference.html#directory_entry-observers refers to https://www.boost.org/doc/libs/1_83_0/libs/filesystem/doc/reference.html#Error-reporting which states:

> Functions having an argument of type system::error_code& report errors as follows, unless otherwise specified:

> If a call by the implementation to an operating system or other underlying API results in an error that prevents the function from meeting its specifications, the system::error_code& argument is set as appropriate for the specific error. Otherwise, clear() is called on the system::error_code& argument.

Here https://github.com/boostorg/filesystem/blob/e65ddb6ef21697970f7d1438f7a46c5233940059/include/boost/filesystem/directory.hpp#L192 `ec` is not reset when the status is already known, which is a behavior change from boost 1.82

**Comment by Lastique** [comment]
Oh, sorry, you mean `directory_entry` members. Those are not [documented](https://www.boost.org/doc/libs/1_83_0/libs/filesystem/doc/reference.html#directory_entry-observers) to call `ec.clear()`, but in std::filesystem they are effectively required to clear the error code.

I'll fix this, thanks for the report.

**Comment by gfgtdf** [comment]
Thanks for fixing this.
