### ISSUE TITLE
Behavior of `absolute("")` in v4

### ISSUE THREAD

**Issue by Pesa** [boostorg/filesystem#301]
(Like #300, I'm not sure if this is a bug or I'm misreading the documentation)

`absolute()` on an empty path is defined as being equal to `absolute(base) / path()`. Let's assume `base` is `/foo`. With Boost Filesystem v4 we get the following:

* `absolute(path())` returns `/foo`
* `absolute(base) / path()` returns `/foo/`

This is because the behavior of `operator/=` changed in v4. Which one is correct?

**Comment by Lastique** [comment]
Both are, according to path modification rules in v3 and v4. This is intended behavior.

**Comment by Pesa** [comment]
Sorry, I'm not sure I understand. What do you mean that both are correct? Is the documentation of `absolute` wrong for v4 then?

**Comment by Lastique** [comment]
In what way is it wrong?

**Comment by Pesa** [comment]
It says:

> Returns: A absolute path composed according to the following table [...] `return absolute(base) / p`

(I'm looking at the bottom right cell)

Not sure what "according to" means formally, but as I said earlier, for an empty path `p`, `absolute(p)` and `absolute(base) / p` give different results in v4.

**Comment by Lastique** [comment]
I'm not sure what the problem is. Yes, the result is different between v3 and v4, and that is as expected. The v4 result is correct - in v4.

**Comment by Pesa** [comment]
I'm not talking about v3, or the difference between v3 and v4. This entire issue is exclusively about v4.

**Comment by Pesa** [comment]
Thanks!
