### ISSUE TITLE
Boost winapi file_management dwReserved bug?

### ISSUE THREAD

**Issue by hoyhoy** [boostorg/filesystem#309]
Detected by msvc /analyze.

```
boost\p\include\boost/winapi/file_management.hpp(494,1): error C2220: the following warning is treated as an error
boost\p\include\boost\winapi\file_management.hpp(493): warning C6388: 'dwReserved' might not be '0':  this does not adhere to the specification for the function 'LockFileEx'
```

**Comment by Lastique** [comment]
1. Boost.Filesystem does not call `LockFileEx`.
2. Boost.WinAPI only forwards arguments to `LockFileEx` that were passed to it by the caller. If the caller passes invalid arguments, that's a problem in the caller.
3. If there is no caller, and MSVC simply generates a warning solely based on the definition of the [`LockFileEx`](https://github.com/boostorg/winapi/blob/39396bd78254053f3137510478e8f956bd2b83d4/include/boost/winapi/file_management.hpp#L485-L494) inline function then the warning is bogus and I'd consider this a bug in the analyzer.

**Comment by hoyhoy** [comment]
Wouldn't it be a whole lot easier if you just ignored in the boost headers rather than dumping the problem into user space?  Our code doesn't even call FileLock.  Just including the header causes the issue.

**Comment by Lastique** [comment]
Please, bring your complaints to Microsoft.
