### ISSUE TITLE
weakly_canonical doesn't seem to work on Windows on pathes starting with "../"

### ISSUE THREAD

**Issue by h01G3r** [boostorg/filesystem#311]
e.g. for the Code
`auto tmp = boost::filesystem::weakly_canonical("../foo", "C:/LocalData");`
I would expect a result of "C:\\foo", but I get "C:\\LocalData\\foo" instead,

This was tested on 1.85.0 release code-base, Windows 10, Visual Studio 2014.

**Comment by Lastique** [comment]
Are you using Boost.Filesystem v3 or v4?

**Comment by Lastique** [comment]
Should be fixed now. Thanks for the report.
