### ISSUE TITLE
Release History can't be found by users in docs

### ISSUE THREAD

**Issue by joaquintides** [boostorg/filesystem#317]
The following page:

https://www.boost.org/libs/filesystem/doc/release_history.html

does not seem to be linked anywhere from the docs:

https://www.boost.org/libs/filesystem

which prevents users from easily accessing it. See [this ML post](https://lists.boost.org/boost-users/2024/07/91593.php) for more context.

**Comment by Lastique** [comment]
The page is reachable through the "Releases" link in the top header on every page of Filesystem docs.
