### ISSUE TITLE
Error in directory.cpp when cross-compiling for older FreeBSD

### ISSUE THREAD

**Issue by alexsharoff** [boostorg/filesystem#328]
`dirfd` is a macro on FreeBSD 8, so compiling the following code fails with `error: expected id-expression before '(' token`:

https://github.com/boostorg/filesystem/blob/fbd23ee0e07ff17d486534314f89d1b5fb306824/src/directory.cpp#L273

**Comment by Lastique** [comment]
Thanks for the report.
