### ISSUE TITLE
hidden virtual function warning

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/filesystem#57]
./boost/detail/utf8_codecvt_facet.hpp:181:17: warning: 'boost::filesystem::detail::utf8_codecvt_facet::do_length' hides overloaded virtual function [-Woverloaded-virtual]

https://travis-ci.org/vinniefalco/beast/jobs/294451968#L1424

**Comment by Lastique** [comment]
`utf8_codecvt_facet` is part of Boost.Detail, please [report](https://github.com/boostorg/detail/issues/new) the problem there if it's still relevant.
