### ISSUE TITLE
relative(path a_child, path a_base) fails if a_base contains symlinks on Windows

### ISSUE THREAD

**Issue by BaileyLove** [boostorg/filesystem#85]
relative() calls weakly_canonical() passing a_base as argument, which in turn calls canonical(), which returns an empty path, and then relative() throws.
The message reads: 
boost::filesystem::relative: The system cannot find the file specified: "T:\src\\_wxWidgets_\\interface\wx"

This _wxWidgets_ is a symlink to _wxWidgets-3.1.0_.
If instead of "T:\src\wxWidgets\interface\wx" I call relative() with "T:\src\wxWidgets-3.1.0\interface\wx", the function succeeds.

**Comment by Lastique** [comment]
Probably fixed by https://github.com/boostorg/filesystem/pull/100.
