### ISSUE TITLE
Trac #7404 "filesystem::canonical fails on UNC paths on Windows" still an issue in 1.68

### ISSUE THREAD

**Issue by Bigpet** [boostorg/filesystem#87]
Original text:

> The filesystem library function canonical(p, base) fails for all UNC paths on Windows because it gets an "invalid path" error when it calls symlink_status at line 816 of operations.cpp. Example: For the path "\\server\share\file", the first time execution reaches line 816 of operations.cpp, it calls is_symlink(detail::symlink_status("server", ec)) and ec is set to the Windows "invalid path" system error code. 

This is still an issue. Minimal program to reproduce:

```
#include <boost/filesystem.hpp>
#include <cstdio>

namespace fs = boost::filesystem;

int main(int argc, const char** argv)
{
	fs::path p(R"(\\localhost\c$)");
	boost::system::error_code ec;
	auto p2 = fs::canonical(p,ec);
	printf("%d", ec.value());
}
```
Only happens on Windows platforms, specifically because of the call to boost::filesystem::detail::symlink_status during filesystem::canonical

**Comment by j-renggli** [comment]
Also a problem with relative paths because it's calling `weakly_canonical` internally. Here's a snippet to reproduce:
```
fs::path root("\\\\localhost\\foo");
fs::path file = root / "bar";
auto rel_path = fs::relative(file, root);
// throws boost::filesystem::relative: Incorrect function: "\\localhost\foo"
```

**Comment by Lastique** [comment]
If Windows doesn't allow to query file status on a remote share then I don't see what I can do in Boost.Filesystem about that.
