### ISSUE TITLE
Boost directory iterator not working with root dirs ie D:\ throws access denied.

### ISSUE THREAD

**Issue by kenkit** [boostorg/filesystem#90]
I had originally posted the issue on the boost repo 
I'll just link it here https://github.com/boostorg/boost/issues/217

**Comment by Lastique** [comment]
Please, describe what the problem is and provide a small reproducer code, if possible. Also, what Boost and compiler are you using?

**Comment by kenkit** [comment]
Sorry I was offline for a while back there.
But this is thee message I had posted originally.
I've experienced the above bug on windows x86 using latest boost.

The said code is below
`  for (boost::filesystem::recursive_directory_iterator end,
         dir(path(file_name));
         dir != end; ++dir) `
I was initially using ` dir(file_name);` when I discovered this.
The error occured only when scanning root drive. ie `F:\ `

I cannot get the list of files in a virtual hard drive on windows platform, the program would crash.
But on normal drive it worked just fine.

**Comment by kenkit** [comment]
Hi it looks as if the problem occurs when there are characters with chinese filenames.
Any help to solve this will be greately appreciated

**Comment by Lastique** [comment]
You still haven't described what the problem is.

**Comment by kenkit** [comment]
I've discovered what the problem is, although I'm not sure if it is possible to implement a workaround.
When directory iterator is scanning the root dir it comes across the recycle bin and other windows directory which it does not have read access to so it throws an access denied error.
I've  tested and confirmed this problem using std::filesystem.
Is there a way to skip this types of files ?
Try running the above code on a root drive, the error is not triggered on some removable drives.

**Comment by kenkit** [comment]
I think I have an idea about how to fix this.
Wrap the directory iterator under a catch statement, then if it fails, skip this directory.

**Comment by kenkit** [comment]
I thin a better solution would be for filesystem to skip this internally but still return the directory name.

**Comment by Lastique** [comment]
You can pass `directory_options::skip_permission_denied` to `recursive_directory_iterator` constructor to avoid recursing into directories to which you don't have permission.

**Comment by kenkit** [comment]
Wow, thank you soo much. This bug has been existing in my project for an year now.
